### ISSUE TITLE
Code manage profile of student

### ISSUE THREAD

**Issue by ChienThangnoT** [ChienThangnoT/online-classrom-information-backend#11]

**Comment by GnuDNaT** [comment]
Add UpdateProfile

**Comment by ChienThangnoT** [comment]
Can not update email

**Comment by GnuDNaT** [comment]
![image](https://github.com/ChienThangnoT/online-classrom-information-backend/assets/107823287/8089096a-f91c-4530-8468-5aa01799c205)
