### ISSUE TITLE
Code manage profile of parent

### ISSUE THREAD

**Issue by ChienThangnoT** [ChienThangnoT/online-classrom-information-backend#12]

**Comment by GnuDNaT** [comment]
Add UpdateProfile

**Comment by ChienThangnoT** [comment]
cannot update email

**Comment by GnuDNaT** [comment]
![image](https://github.com/ChienThangnoT/online-classrom-information-backend/assets/107823287/1bcf3122-8196-41c0-966b-f194c9a28ecc)
