### ISSUE TITLE
Code function add Course with related field

### ISSUE THREAD

**Issue by ChienThangnoT** [ChienThangnoT/online-classrom-information-backend#22]
Ask mr.Long :)

**Comment by GnuDNaT** [comment]
![image](https://github.com/ChienThangnoT/online-classrom-information-backend/assets/107823287/bb917599-537b-4a52-a9d9-6d9741ba5e53)
![image](https://github.com/ChienThangnoT/online-classrom-information-backend/assets/107823287/8c61ad5d-66a0-4a17-9576-5f268cc44e9f)
![image](https://github.com/ChienThangnoT/online-classrom-information-backend/assets/107823287/33be57f0-dc98-48c2-8847-337e24e478ca)
![image](https://github.com/ChienThangnoT/online-classrom-information-backend/assets/107823287/089abbfe-3c99-4303-86c6-4735d8cfdc25)
![image](https://github.com/ChienThangnoT/online-classrom-information-backend/assets/107823287/ed6bb9f7-a840-4ea3-93db-08541faea30f)
![image](https://github.com/ChienThangnoT/online-classrom-information-backend/assets/107823287/5cc3d3a1-dc7a-4705-af69-11e8f953eaf0)
![image](https://github.com/ChienThangnoT/online-classrom-information-backend/assets/107823287/1780f2c5-8a4d-4baa-bcaa-f24235e1b83b)
![image](https://github.com/ChienThangnoT/online-classrom-information-backend/assets/107823287/c2cc6267-b492-4412-a4c5-c2722824b39b)
![image](https://github.com/ChienThangnoT/online-classrom-information-backend/assets/107823287/58b42641-9e32-475b-aefe-19ebc3a3f424)
![image](https://github.com/ChienThangnoT/online-classrom-information-backend/assets/107823287/e9aa267f-483e-4712-b8f9-d0e9bd007803)
