### ISSUE TITLE
Update course

### ISSUE THREAD

**Issue by ChienThangnoT** [ChienThangnoT/online-classrom-information-backend#23]
View SRS

**Comment by GnuDNaT** [comment]
Update Course
![image](https://github.com/ChienThangnoT/online-classrom-information-backend/assets/107823287/14a09509-30a5-4a4c-a5d1-375ff11e9998)
![image](https://github.com/ChienThangnoT/online-classrom-information-backend/assets/107823287/02e05cf9-fc00-4f6a-bf4c-89efd90fc5be)
![image](https://github.com/ChienThangnoT/online-classrom-information-backend/assets/107823287/efa7f744-913f-4afd-86f1-819da83c7b26)
![image](https://github.com/ChienThangnoT/online-classrom-information-backend/assets/107823287/a0566404-fcd2-4caf-8646-c4b4441e113e)
![image](https://github.com/ChienThangnoT/online-classrom-information-backend/assets/107823287/899a6b4a-ab17-42f0-ad6a-0b5e841a62a6)
![image](https://github.com/ChienThangnoT/online-classrom-information-backend/assets/107823287/19c90a77-f4bd-49e8-8d46-c703d45e99ba)

**Comment by GnuDNaT** [comment]
Update Section
![image](https://github.com/ChienThangnoT/online-classrom-information-backend/assets/107823287/cd92ff98-a7ed-413e-8102-c4e32bd3965e)
![image](https://github.com/ChienThangnoT/online-classrom-information-backend/assets/107823287/3a7f5bc2-7115-4df4-b9b7-e0710b59ba09)
![image](https://github.com/ChienThangnoT/online-classrom-information-backend/assets/107823287/ad744bd4-ed4e-4f6f-b954-c3773bf4aea8)
![image](https://github.com/ChienThangnoT/online-classrom-information-backend/assets/107823287/32c57ae4-33f4-4d8c-a6ea-d3ed8ecaad5b)

**Comment by GnuDNaT** [comment]
Update Step
![image](https://github.com/ChienThangnoT/online-classrom-information-backend/assets/107823287/b29ceec7-b9d0-49da-ad50-7260aaea66c0)
![image](https://github.com/ChienThangnoT/online-classrom-information-backend/assets/107823287/5e5e94ba-ec73-4727-9c62-410179a41ba3)
![image](https://github.com/ChienThangnoT/online-classrom-information-backend/assets/107823287/6eebe57d-5647-47ac-8dbb-102ee10ea75b)
![image](https://github.com/ChienThangnoT/online-classrom-information-backend/assets/107823287/dc260755-2d9a-4be6-b4d6-51fc78441c63)
